[server]
host: 0.0.0.0
port: 7125
klippy_uds_address: /tmp/klippy_uds
max_upload_size: 1024
#enable_debug_logging: False

[file_manager]
queue_gcode_uploads: False
enable_object_processing: True

[database]
#enable_database_debug: False

[data_store]
temperature_store_size: 600
gcode_store_size: 1000

[machine]
provider: systemd_dbus
validate_service: False
validate_config: False

[authorization]
force_logins: False
cors_domains:
  *.local
  *.lan
  *://app.fluidd.xyz
  *://k2
  *://k2:*
  *://k2.local
  *://k2.local:*

trusted_clients:
  10.0.0.0/8
  127.0.0.0/8
  169.254.0.0/16
  172.16.0.0/12
  192.168.0.0/16
  198.19.0.0/16
  FE80::/10
  ::1/128
[octoprint_compat]

[history]

[timelapse]
output_path: /mnt/UDISK/printer_data/timelapse
frame_path: /mnt/UDISK/printer_data/timelapse_frames

# [spoolman]
# server: http://192.168.1.5:7912
# sync_rate: 5

[update_manager]
refresh_interval: 168
enable_auto_refresh: True
enable_system_updates: False

[update_manager klipper]
channel: dev
report_anomalies: False

[update_manager mainsail]
repo: mainsail-crew/mainsail
type: web
channel: stable
path: ~/mainsail

[update_manager moonraker]
channel: stable

[update_manager fluidd]
type: web
repo: KennethDoerflein/fluidd
path: ~/fluidd

[update_manager cartographer_plugin]
type: python
channel: stable
virtualenv: ~/klippy-env
project_name: cartographer3d-plugin
is_system_service: False
managed_services: klipper
info_tags: desc=Cartographer Plugin

[update_manager helixscreen]
type: web
repo: prestonbrown/helixscreen
path: /mnt/UDISK/helixscreen
channel: stable